package com.pojo;

// Generated 28 Jan, 2019 6:23:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Bookedticket generated by hbm2java
 */
public class Bookedticket implements java.io.Serializable {

	private Integer bookingid;
	private Flight flight;
	private Registrationdata registrationdata;

	public Bookedticket() {
	}

	public Bookedticket(Flight flight, Registrationdata registrationdata) {
		this.flight = flight;
		this.registrationdata = registrationdata;
	}

	public Integer getBookingid() {
		return this.bookingid;
	}

	public void setBookingid(Integer bookingid) {
		this.bookingid = bookingid;
	}

	public Flight getFlight() {
		return this.flight;
	}

	public void setFlight(Flight flight) {
		this.flight = flight;
	}

	public Registrationdata getRegistrationdata() {
		return this.registrationdata;
	}

	public void setRegistrationdata(Registrationdata registrationdata) {
		this.registrationdata = registrationdata;
	}

}
