package com.pojo;

// Generated 28 Jan, 2019 6:23:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cabs generated by hbm2java
 */
public class Cabs implements java.io.Serializable {

	private Integer cabid;
	private Registrationdata registrationdata;
	private String drivername;
	private String cabname;
	private String cabtype;
	private String package_;
	private String cabimg;
	private String cabno;
	private String phoneno;
	private Set cabbookings = new HashSet(0);

	public Cabs() {
	}

	public Cabs(Registrationdata registrationdata, String drivername, String cabname, String cabtype, String package_,
			String cabimg, String cabno, String phoneno, Set cabbookings) {
		this.registrationdata = registrationdata;
		this.drivername = drivername;
		this.cabname = cabname;
		this.cabtype = cabtype;
		this.package_ = package_;
		this.cabimg = cabimg;
		this.cabno = cabno;
		this.phoneno = phoneno;
		this.cabbookings = cabbookings;
	}

	public Integer getCabid() {
		return this.cabid;
	}

	public void setCabid(Integer cabid) {
		this.cabid = cabid;
	}

	public Registrationdata getRegistrationdata() {
		return this.registrationdata;
	}

	public void setRegistrationdata(Registrationdata registrationdata) {
		this.registrationdata = registrationdata;
	}

	public String getDrivername() {
		return this.drivername;
	}

	public void setDrivername(String drivername) {
		this.drivername = drivername;
	}

	public String getCabname() {
		return this.cabname;
	}

	public void setCabname(String cabname) {
		this.cabname = cabname;
	}

	public String getCabtype() {
		return this.cabtype;
	}

	public void setCabtype(String cabtype) {
		this.cabtype = cabtype;
	}

	public String getPackage_() {
		return this.package_;
	}

	public void setPackage_(String package_) {
		this.package_ = package_;
	}

	public String getCabimg() {
		return this.cabimg;
	}

	public void setCabimg(String cabimg) {
		this.cabimg = cabimg;
	}

	public String getCabno() {
		return this.cabno;
	}

	public void setCabno(String cabno) {
		this.cabno = cabno;
	}

	public String getPhoneno() {
		return this.phoneno;
	}

	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

	public Set getCabbookings() {
		return this.cabbookings;
	}

	public void setCabbookings(Set cabbookings) {
		this.cabbookings = cabbookings;
	}

}
