package com.pojo;

// Generated 28 Jan, 2019 6:23:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Hotelbooking generated by hbm2java
 */
public class Hotelbooking implements java.io.Serializable {

	private Integer hbookid;
	private Hotel hotel;
	private Registrationdata registrationdata;
	private Date bookingdate;
	private String noofpeople;

	public Hotelbooking() {
	}

	public Hotelbooking(Hotel hotel, Registrationdata registrationdata, Date bookingdate, String noofpeople) {
		this.hotel = hotel;
		this.registrationdata = registrationdata;
		this.bookingdate = bookingdate;
		this.noofpeople = noofpeople;
	}

	public Integer getHbookid() {
		return this.hbookid;
	}

	public void setHbookid(Integer hbookid) {
		this.hbookid = hbookid;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public Registrationdata getRegistrationdata() {
		return this.registrationdata;
	}

	public void setRegistrationdata(Registrationdata registrationdata) {
		this.registrationdata = registrationdata;
	}

	public Date getBookingdate() {
		return this.bookingdate;
	}

	public void setBookingdate(Date bookingdate) {
		this.bookingdate = bookingdate;
	}

	public String getNoofpeople() {
		return this.noofpeople;
	}

	public void setNoofpeople(String noofpeople) {
		this.noofpeople = noofpeople;
	}

}
