package com.pojo;

// Generated 28 Jan, 2019 6:23:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel implements java.io.Serializable {

	private Integer hid;
	private Registrationdata registrationdata;
	private String hotelname;
	private String hoteltype;
	private Integer rent;
	private String hotelinfo;
	private String hotelimage;
	private String hoteladdress;
	private Set hotelbookings = new HashSet(0);

	public Hotel() {
	}

	public Hotel(Registrationdata registrationdata, String hotelname, String hoteltype, Integer rent, String hotelinfo,
			String hotelimage, String hoteladdress, Set hotelbookings) {
		this.registrationdata = registrationdata;
		this.hotelname = hotelname;
		this.hoteltype = hoteltype;
		this.rent = rent;
		this.hotelinfo = hotelinfo;
		this.hotelimage = hotelimage;
		this.hoteladdress = hoteladdress;
		this.hotelbookings = hotelbookings;
	}

	public Integer getHid() {
		return this.hid;
	}

	public void setHid(Integer hid) {
		this.hid = hid;
	}

	public Registrationdata getRegistrationdata() {
		return this.registrationdata;
	}

	public void setRegistrationdata(Registrationdata registrationdata) {
		this.registrationdata = registrationdata;
	}

	public String getHotelname() {
		return this.hotelname;
	}

	public void setHotelname(String hotelname) {
		this.hotelname = hotelname;
	}

	public String getHoteltype() {
		return this.hoteltype;
	}

	public void setHoteltype(String hoteltype) {
		this.hoteltype = hoteltype;
	}

	public Integer getRent() {
		return this.rent;
	}

	public void setRent(Integer rent) {
		this.rent = rent;
	}

	public String getHotelinfo() {
		return this.hotelinfo;
	}

	public void setHotelinfo(String hotelinfo) {
		this.hotelinfo = hotelinfo;
	}

	public String getHotelimage() {
		return this.hotelimage;
	}

	public void setHotelimage(String hotelimage) {
		this.hotelimage = hotelimage;
	}

	public String getHoteladdress() {
		return this.hoteladdress;
	}

	public void setHoteladdress(String hoteladdress) {
		this.hoteladdress = hoteladdress;
	}

	public Set getHotelbookings() {
		return this.hotelbookings;
	}

	public void setHotelbookings(Set hotelbookings) {
		this.hotelbookings = hotelbookings;
	}

}
