package com.pojo;

// Generated 28 Jan, 2019 6:23:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Registrationdata generated by hbm2java
 */
public class Registrationdata implements java.io.Serializable {

	private Integer rid;
	private Roll roll;
	private String firstname;
	private String lastname;
	private String email;
	private String password;
	private String mobile;
	private String country;
	private Set cabbookings = new HashSet(0);
	private Set cabses = new HashSet(0);
	private Set hotels = new HashSet(0);
	private Set flights = new HashSet(0);
	private Set bookedtickets = new HashSet(0);
	private Set tourguidebookings = new HashSet(0);
	private Set hotelbookings = new HashSet(0);
	private Set tourguides = new HashSet(0);

	public Registrationdata() {
	}

	public Registrationdata(Roll roll, String firstname, String lastname, String email, String password, String mobile,
			String country, Set cabbookings, Set cabses, Set hotels, Set flights, Set bookedtickets,
			Set tourguidebookings, Set hotelbookings, Set tourguides) {
		this.roll = roll;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.password = password;
		this.mobile = mobile;
		this.country = country;
		this.cabbookings = cabbookings;
		this.cabses = cabses;
		this.hotels = hotels;
		this.flights = flights;
		this.bookedtickets = bookedtickets;
		this.tourguidebookings = tourguidebookings;
		this.hotelbookings = hotelbookings;
		this.tourguides = tourguides;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public Roll getRoll() {
		return this.roll;
	}

	public void setRoll(Roll roll) {
		this.roll = roll;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set getCabbookings() {
		return this.cabbookings;
	}

	public void setCabbookings(Set cabbookings) {
		this.cabbookings = cabbookings;
	}

	public Set getCabses() {
		return this.cabses;
	}

	public void setCabses(Set cabses) {
		this.cabses = cabses;
	}

	public Set getHotels() {
		return this.hotels;
	}

	public void setHotels(Set hotels) {
		this.hotels = hotels;
	}

	public Set getFlights() {
		return this.flights;
	}

	public void setFlights(Set flights) {
		this.flights = flights;
	}

	public Set getBookedtickets() {
		return this.bookedtickets;
	}

	public void setBookedtickets(Set bookedtickets) {
		this.bookedtickets = bookedtickets;
	}

	public Set getTourguidebookings() {
		return this.tourguidebookings;
	}

	public void setTourguidebookings(Set tourguidebookings) {
		this.tourguidebookings = tourguidebookings;
	}

	public Set getHotelbookings() {
		return this.hotelbookings;
	}

	public void setHotelbookings(Set hotelbookings) {
		this.hotelbookings = hotelbookings;
	}

	public Set getTourguides() {
		return this.tourguides;
	}

	public void setTourguides(Set tourguides) {
		this.tourguides = tourguides;
	}

}
