package com.pojo;

// Generated 28 Jan, 2019 6:23:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Roll generated by hbm2java
 */
public class Roll implements java.io.Serializable {

	private Integer rollid;
	private String rollname;
	private Set registrationdatas = new HashSet(0);

	public Roll() {
	}

	public Roll(String rollname, Set registrationdatas) {
		this.rollname = rollname;
		this.registrationdatas = registrationdatas;
	}

	public Integer getRollid() {
		return this.rollid;
	}

	public void setRollid(Integer rollid) {
		this.rollid = rollid;
	}

	public String getRollname() {
		return this.rollname;
	}

	public void setRollname(String rollname) {
		this.rollname = rollname;
	}

	public Set getRegistrationdatas() {
		return this.registrationdatas;
	}

	public void setRegistrationdatas(Set registrationdatas) {
		this.registrationdatas = registrationdatas;
	}

}
