package com.pojo;

// Generated 28 Jan, 2019 6:23:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tourguide generated by hbm2java
 */
public class Tourguide implements java.io.Serializable {

	private Integer tid;
	private Registrationdata registrationdata;
	private String guidename;
	private String guideid;
	private Integer guidecost;
	private String guidephoto;
	private String gender;
	private String phoneno;
	private Set tourguidebookings = new HashSet(0);

	public Tourguide() {
	}

	public Tourguide(Registrationdata registrationdata, String guidename, String guideid, Integer guidecost,
			String guidephoto, String gender, String phoneno, Set tourguidebookings) {
		this.registrationdata = registrationdata;
		this.guidename = guidename;
		this.guideid = guideid;
		this.guidecost = guidecost;
		this.guidephoto = guidephoto;
		this.gender = gender;
		this.phoneno = phoneno;
		this.tourguidebookings = tourguidebookings;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public Registrationdata getRegistrationdata() {
		return this.registrationdata;
	}

	public void setRegistrationdata(Registrationdata registrationdata) {
		this.registrationdata = registrationdata;
	}

	public String getGuidename() {
		return this.guidename;
	}

	public void setGuidename(String guidename) {
		this.guidename = guidename;
	}

	public String getGuideid() {
		return this.guideid;
	}

	public void setGuideid(String guideid) {
		this.guideid = guideid;
	}

	public Integer getGuidecost() {
		return this.guidecost;
	}

	public void setGuidecost(Integer guidecost) {
		this.guidecost = guidecost;
	}

	public String getGuidephoto() {
		return this.guidephoto;
	}

	public void setGuidephoto(String guidephoto) {
		this.guidephoto = guidephoto;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPhoneno() {
		return this.phoneno;
	}

	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

	public Set getTourguidebookings() {
		return this.tourguidebookings;
	}

	public void setTourguidebookings(Set tourguidebookings) {
		this.tourguidebookings = tourguidebookings;
	}

}
